### ISSUE TITLE
Crash on Version Detection

### ISSUE THREAD

**Issue by codengine** [Kawa-oneechan/SCICompanion#20]
I'm using the latest build from here
https://github.com/Kawa-oneechan/SCICompanion/actions/runs/5442185766

and the application just straight crashes when I do that with Space Quest 1 or Space Quest 4, I guess it is unrelated to the game.

I have no logs that I could provide (or dont know where they are).

**Comment by Kawa-oneechan** [comment]
I may have been a bit over-eager when I found out where MFC lists get their starting contents from. Version Detection has a lot of dropdown combo boxes, so there's a lot of places I can mess up. Fortunately, it seems it's _only_ Version Detection I need to doublecheck.

The problem is this: MFC uses `DLGINIT` resources to fill in list contents, with its own weird little format. In the .rc file, this format is rather unreadable with the actual text strings encoded as a series of integers..
```rc
IDD_DIALOGVERSION DLGINIT
BEGIN
    IDC_COMBO1, 0x403, 4, 0
0x4745, 0x0041,
    IDC_COMBO1, 0x403, 6, 0
0x4756, 0x2041, 0x0031,
    IDC_COMBO1, 0x403, 8, 0
0x4756, 0x2041, 0x2e31, 0x0031,
//etc...
    0
END
```
You'll note that `EGA` is `0x45 0x47 0x41`, plus the terminating null.
Something much more readable would be
```rc
IDD_DIALOGVERSION DLGINIT
BEGIN
    IDC_COMBO1, 0x403, 4, 0, "EGA\0"
    IDC_COMBO1, 0x403, 6, 0, "VGA 1\0"
    IDC_COMBO1, 0x403, 8, 0, "VGA 1.1\0"
//etc...
    0
END
```
(Unfortunately, the "\0" is required -- using a bare `"EGA"` would store only three characters, and `"EGA" 0` would store two nulls as a short and throw off the format.)

And throwing off the format is what happened here: _I accidentally specified a six-character string but only wrote `"VGA\0"`, which is four._

**Comment by codengine** [comment]
It seems to work now, thanks!
